packages:
  - apps/*
  - packages/*

catalogs:
  next:
    next: 16.1.6
  node:
    '@types/node': 25.2.1
  postcss:
    postcss: 8.5.6
  react:
    '@types/react': 19.2.13
    '@types/react-dom': 19.2.3
    react: 19.2.4
    react-dom: 19.2.4
    react-router: 7.13.1
  tailwind:
    '@tailwindcss/postcss': 4.1.18
    '@tailwindcss/vite': 4.1.18
    tailwindcss: 4.1.18
  typescript:
    typescript: 5.9.3
  vite:
    '@vitejs/plugin-react-swc': 4.2.3
    vite: 7.3.1

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - core-js-pure
  - esbuild
  - msw